-- VHDL module instantiation generated by SCUBA Diamond_1.4_Production (87)
-- Module  Version: 5.2
-- Sat Jul 21 22:17:04 2012

-- parameterized module component declaration
component Pll125to50
    port (CLK: in std_logic; CLKOP: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : Pll125to50
    port map (CLK=>__, CLKOP=>__, LOCK=>__);
