-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.2.446
-- Module  Version: 5.7
-- Thu Dec 17 15:55:54 2020

-- parameterized module component declaration
component Pll125to50
    port (CLK: in std_logic; CLKOP: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : Pll125to50
    port map (CLK=>__, CLKOP=>__, LOCK=>__);
