-- VHDL module instantiation generated by SCUBA Diamond_1.4_Production (87)
-- Module  Version: 5.2
-- Sat Jul 21 20:10:48 2012

-- parameterized module component declaration
component Pll125to100x50
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOK: out std_logic; 
        LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : Pll125to100x50
    port map (CLK=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);
